require "./spec_helper"

# Reference scores generated by the FIRST CVSS v4.0 calculator
# (https://www.first.org/cvss/calculator/4.0).
private def parse(s)
  CVSS::V4::Vector.parse(s)
end

describe CVSS::V4::Vector do
  describe ".parse" do
    it "parses a canonical v4 vector" do
      v = parse("CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N")
      v.version.should eq("4.0")
      v.av.should eq(CVSS::V4::AttackVector::Network)
      v.vc.should eq(CVSS::V4::VulnerableImpact::High)
    end

    it "rejects missing base metrics" do
      expect_raises(CVSS::ParseError, /missing required/) do
        parse("CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N")
      end
    end

    it "rejects unknown metrics" do
      expect_raises(CVSS::ParseError, /unknown/) do
        parse("CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N/XX:Y")
      end
    end

    it "accepts optional Threat / Environmental / Supplemental metrics" do
      s = "CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N" \
          "/E:A/CR:H/IR:H/AR:H/MAV:N/MAC:L/MAT:N/MPR:N/MUI:N/MVC:H/MVI:H/MVA:H" \
          "/MSC:N/MSI:N/MSA:N/S:N/AU:N/R:A/V:D/RE:L/U:Clear"
      v = parse(s)
      v.e.should eq(CVSS::V4::ExploitMaturity::Attacked)
      v.u.should eq(CVSS::V4::ProviderUrgency::Clear)
    end
  end

  describe "base_score" do
    it "returns 0.0 when every impact is None (shortcut)" do
      v = parse("CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:N/VI:N/VA:N/SC:N/SI:N/SA:N")
      v.base_score.should eq(0.0)
      v.severity.should eq(CVSS::Severity::None)
    end

    it "scores 9.3 for a fully-network HHH base" do
      v = parse("CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N")
      v.base_score.should eq(9.3)
      v.severity.should eq(CVSS::Severity::Critical)
    end

    it "macro-vector for fully-network HHH-base is 000200" do
      v = parse("CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N")
      CVSS::V4::Score.macro_vector(v).should eq("000200")
    end

    it "scores 7.0 for a physical-only fully-impacting attack" do
      # macro: 200200 → table lookup 7.0 (no further severity-distance pull).
      v = parse("CVSS:4.0/AV:P/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N")
      v.base_score.should eq(7.0)
    end

    it "honors E:U downgrade" do
      hi = parse("CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N")
      lo = parse("CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N/E:U")
      lo.base_score.should be < hi.base_score
    end

    it "honors a Modified base override" do
      base = parse("CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N")
      patched = parse("CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N/MAV:P")
      patched.base_score.should be < base.base_score
    end
  end

  describe "metric_value" do
    it "returns short codes for base metrics" do
      v = parse("CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N")
      v.metric_value("AV").should eq("N")
      v.metric_value("VC").should eq("H")
      v.metric_value("SA").should eq("N")
    end

    it "returns 'X' for unset optional metrics" do
      v = parse("CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N")
      v.metric_value("E").should eq("X")
      v.metric_value("MSI").should eq("X")
      v.metric_value("U").should eq("X")
    end

    it "returns the stored code for set optional metrics" do
      v = parse("CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N/E:A/MSI:S/U:Red")
      v.metric_value("E").should eq("A")
      v.metric_value("MSI").should eq("S")
      v.metric_value("U").should eq("Red")
    end
  end

  describe "Subsequent System impact paths" do
    it "EQ4=1 when SC/SI/SA include H but no Safety override" do
      v = parse("CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:N/VI:N/VA:N/SC:H/SI:H/SA:H")
      v.macro_vector[3].should eq('1')
      v.base_score.should eq(7.9)
    end

    it "MSI:S forces EQ4=0 (Safety override)" do
      v = parse("CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N/MSI:S")
      v.macro_vector[3].should eq('0')
      v.base_score.should eq(10.0)
    end

    it "MSA:S also forces EQ4=0" do
      v = parse("CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N/MSA:S")
      v.macro_vector[3].should eq('0')
    end
  end

  describe "Modified base overrides" do
    it "MVC:N overrides VC:H in scoring" do
      base = parse("CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N")
      with_override = parse("CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N/MVC:N")
      with_override.base_score.should be < base.base_score
      with_override.macro_vector[2].should_not eq(base.macro_vector[2])
    end
  end

  describe "Threat (E) levels" do
    it "shifts EQ5 to 1 for E:P (POC)" do
      v = parse("CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N/E:P")
      v.macro_vector[4].should eq('1')
      v.base_score.should eq(8.9)
    end
  end

  describe "effective_code defaults" do
    it "E:X resolves to A (Attacked / worst case)" do
      v = parse("CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N")
      v.effective_code("E").should eq("A")
    end

    it "CR/IR/AR :X resolve to H" do
      v = parse("CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N")
      v.effective_code("CR").should eq("H")
      v.effective_code("IR").should eq("H")
      v.effective_code("AR").should eq("H")
    end

    it "Modified base metrics override the base when not X" do
      v = parse("CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N/MAV:P")
      v.effective_code("AV").should eq("P") # MAV overrides AV
    end

    it "Modified MSI/MSA do NOT trigger an M-prefix lookup (no MMSI)" do
      # Per spec: m("MSI") returns the raw MSI value. Setting MSI:S should
      # surface as effective_code("MSI") == "S".
      v = parse("CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N/MSI:S")
      v.effective_code("MSI").should eq("S")
    end
  end

  describe "Nomenclature (spec §6)" do
    it "classifies a base-only vector as CVSS-B" do
      v = parse("CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N")
      v.nomenclature.should eq(CVSS::V4::Nomenclature::Base)
      v.nomenclature.to_s.should eq("CVSS-B")
    end

    it "classifies E-set as CVSS-BT" do
      v = parse("CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N/E:A")
      v.nomenclature.should eq(CVSS::V4::Nomenclature::BaseThreat)
      v.nomenclature.to_s.should eq("CVSS-BT")
    end

    it "classifies any environmental as CVSS-BE" do
      v = parse("CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N/MAV:P")
      v.nomenclature.should eq(CVSS::V4::Nomenclature::BaseEnvironmental)
      v.nomenclature.to_s.should eq("CVSS-BE")
    end

    it "classifies threat + environmental as CVSS-BTE" do
      v = parse("CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N/E:A/MAV:P")
      v.nomenclature.should eq(CVSS::V4::Nomenclature::BaseThreatEnvironmental)
      v.nomenclature.to_s.should eq("CVSS-BTE")
    end

    it "treats explicit X as 'not set' (E:X is still CVSS-B)" do
      v = parse("CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N/E:X")
      v.nomenclature.should eq(CVSS::V4::Nomenclature::Base)
    end

    it "treats explicit X env metrics as 'not set' (CR:X is still CVSS-B)" do
      v = parse("CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N/CR:X/MAV:X")
      v.nomenclature.should eq(CVSS::V4::Nomenclature::Base)
    end

    it "supplemental metrics never change the nomenclature" do
      v = parse("CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N/U:Red/AU:Y/R:I/V:C/RE:H/S:P")
      v.nomenclature.should eq(CVSS::V4::Nomenclature::Base)
    end

    it "any of CR/IR/AR set is CVSS-BE" do
      parse("CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N/CR:H").nomenclature.should eq(CVSS::V4::Nomenclature::BaseEnvironmental)
      parse("CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N/IR:M").nomenclature.should eq(CVSS::V4::Nomenclature::BaseEnvironmental)
      parse("CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N/AR:L").nomenclature.should eq(CVSS::V4::Nomenclature::BaseEnvironmental)
    end

    it "any modified subsequent metric set is CVSS-BE" do
      parse("CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N/MSI:S").nomenclature.should eq(CVSS::V4::Nomenclature::BaseEnvironmental)
    end

    it "exposes threat_set? / environmental_set? predicates" do
      base = parse("CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N")
      base.threat_set?.should be_false
      base.environmental_set?.should be_false

      bte = parse("CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N/E:A/MAV:P")
      bte.threat_set?.should be_true
      bte.environmental_set?.should be_true
    end

    it "auto-generated enum predicates work" do
      n = CVSS::V4::Nomenclature::BaseThreatEnvironmental
      n.base_threat_environmental?.should be_true
      n.base?.should be_false
    end
  end

  describe "macro_vector" do
    it "is exposed as an instance method" do
      v = parse("CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N")
      v.macro_vector.should eq("000200")
    end

    it "shifts when E:U downgrades EQ5 to 2" do
      v = parse("CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N/E:U")
      v.macro_vector[4].should eq('2')
    end
  end

  describe ".parse?" do
    it "returns nil on bad input" do
      CVSS::V4::Vector.parse?("CVSS:4.0/AV:Q").should be_nil
    end

    it "returns the vector on success" do
      v = CVSS::V4::Vector.parse?("CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N")
      v.should_not be_nil
      v.not_nil!.base_score.should eq(9.3)
    end
  end

  describe "Equality" do
    it "two parsed v4 vectors with the same string are ==" do
      a = parse("CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N")
      b = parse("CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N")
      a.should eq(b)
      a.hash.should eq(b.hash)
    end
  end

  describe "Classification helpers" do
    it "tags vulnerable-system impact and subsequent-system impact independently" do
      v = parse("CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:H/SI:H/SA:H")
      v.network?.should be_true
      v.impacts_confidentiality?.should be_true
      v.impacts_subsequent_system?.should be_true
    end

    it "subsequent-system impact false when SC/SI/SA all None" do
      v = parse("CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N")
      v.impacts_subsequent_system?.should be_false
    end

    it "covers all four AV branches" do
      parse("CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N").network?.should be_true
      parse("CVSS:4.0/AV:A/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N").adjacent_network?.should be_true
      parse("CVSS:4.0/AV:L/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N").local?.should be_true
      parse("CVSS:4.0/AV:P/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N").physical?.should be_true
    end

    it "tracks PR and CIA helpers" do
      base = parse("CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:N/VA:N/SC:N/SI:N/SA:N")
      base.requires_privileges?.should be_false
      base.impacts_confidentiality?.should be_true
      base.impacts_integrity?.should be_false
      base.impacts_availability?.should be_false

      privileged = parse("CVSS:4.0/AV:N/AC:L/AT:N/PR:H/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N")
      privileged.requires_privileges?.should be_true
    end

    it "v4 user interaction includes Passive (P) and Active (A)" do
      passive = parse("CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:P/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N")
      active = parse("CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:A/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N")
      passive.requires_user_interaction?.should be_true
      active.requires_user_interaction?.should be_true
    end
  end

  describe "to_h" do
    it "returns base metric short-codes in canonical order" do
      v = parse("CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N")
      h = v.to_h
      h["AV"].should eq("N")
      h["VC"].should eq("H")
      h["SA"].should eq("N")
    end

    it "preserves the full-word value for Provider Urgency (U)" do
      v = parse("CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N/U:Red")
      v.to_h["U"].should eq("Red")
    end

    it "captures every modified-base, threat, env, and supplemental metric" do
      s = "CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N" \
          "/E:A/CR:H/IR:H/AR:H/MAV:N/MAC:L/MAT:N/MPR:N/MUI:N/MVC:H/MVI:H/MVA:H" \
          "/MSC:N/MSI:N/MSA:N/S:N/AU:N/R:A/V:D/RE:L/U:Clear"
      h = parse(s).to_h
      %w[E CR IR AR MAV MAC MAT MPR MUI MVC MVI MVA MSC MSI MSA S AU R V RE U].each do |k|
        h.has_key?(k).should be_true
      end
      h["U"].should eq("Clear")
      h["MSI"].should eq("N")
    end
  end

  describe "to_s" do
    it "round-trips a base-only vector" do
      s = "CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N"
      parse(s).to_s.should eq(s)
    end

    it "round-trips a fully-loaded vector" do
      s = "CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N" \
          "/E:A/CR:H/IR:H/AR:H/MAV:N/MAC:L/MAT:N/MPR:N/MUI:N/MVC:H/MVI:H/MVA:H" \
          "/MSC:N/MSI:N/MSA:N/S:N/AU:N/R:A/V:D/RE:L/U:Clear"
      parse(s).to_s.should eq(s)
    end
  end
end
